name: deploy
on:
  release:
    types: [published]
permissions:
  id-token: write  # Required for NPM Publish OIDC
  contents: read
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4
  build:
      needs: setup
      permissions:
        contents: read
        pull-requests: write
        id-token: write  # Required for NPM Publish OIDC
      uses: web-illinois/toolkit-management/.github/workflows/component_deploy.yml@main
      with:
        COMPONENT_NAME: ${{github.event.repository.name}}
        TOOLKIT_AWS_ACCESS_KEY: ${{ vars.TOOLKIT_AWS_ACCESS_KEY }}
        TOOLKIT_AWS_CLOUDFRONT: ${{ vars.TOOLKIT_AWS_CLOUDFRONT }}
        TOOLKIT_AWS_CLOUDFRONT_DEV: ${{ vars.TOOLKIT_AWS_CLOUDFRONT_DEV }}
      secrets:
        TOOLKIT_AWS_ACCESS_SECRET: ${{ secrets.TOOLKIT_AWS_ACCESS_SECRET }}
